<a href="https://colab.research.google.com/github/Choiseoyeon-hub/Data-Science-and-Analysis/blob/main/4%EC%A3%BC%EC%B0%A8_NumPy%EC%99%80_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**8.패키지와 라이브러리**

1)라이브러리

2)패키지

3)내장 함수

In [1]:
# 내장함수 예 : input
strText = input("아무 문장이나 입력하세요 : ")
print(strText)

아무 문장이나 입력하세요 : 테스트
테스트


4)외장 패키지 설치

5)파이썬 주요 패키지

**9.NumPy**

1)List를 사용한 다차원 배열

In [2]:
# List를 이용한 다차원 배열
flVal = [1.0, 2.0, 3.14, 4.2, 5.1]  # 실수 list를 생성

In [3]:
# flVal 3개를 리스트로 구성하여 arVal 다차원 배열을 생성
arVal = [flVal, flVal, flVal]
arVal

[[1.0, 2.0, 3.14, 4.2, 5.1],
 [1.0, 2.0, 3.14, 4.2, 5.1],
 [1.0, 2.0, 3.14, 4.2, 5.1]]

In [4]:
# arVal은 다차원 배열이므로, arVal[n] 인덱스 연산을 통해 n차원 배열 값을 출력
arVal[0]

[1.0, 2.0, 3.14, 4.2, 5.1]

In [5]:
arVal[1]

[1.0, 2.0, 3.14, 4.2, 5.1]

In [6]:
arVal[1][2]

3.14

In [7]:
# 1 차원 값을 변환하여 다른 값을 대입 했을때의 다차원 배열
arVal[0] = 'python'
arVal

['python', [1.0, 2.0, 3.14, 4.2, 5.1], [1.0, 2.0, 3.14, 4.2, 5.1]]

In [8]:
arVal[0][2]

't'

In [9]:
arVal[0] = 'python programming'
arVal

['python programming', [1.0, 2.0, 3.14, 4.2, 5.1], [1.0, 2.0, 3.14, 4.2, 5.1]]

2.Numpy 배열

In [10]:
# numpy 패치지를 import 
import numpy as np
arData = np.array([1.0, 2.0, 3.14, 4.2, 5.1])
arData

array([1.  , 2.  , 3.14, 4.2 , 5.1 ])

In [11]:
# 배열 각 요소의 합을 출력
arData.sum()

15.44

In [12]:
arVal.sum()

AttributeError: ignored

In [ ]:
print(type(arVal))
print(type(arData))

In [14]:
# 배열에 대한 표준편차 출력
arData.std()

1.4717934637713266

In [15]:
# 배열의 누적 합을 출력
arData.cumsum()

array([ 1.  ,  3.  ,  6.14, 10.34, 15.44])

In [16]:
arData * 2

array([ 2.  ,  4.  ,  6.28,  8.4 , 10.2 ])

In [17]:
arData ** 2 # 2를 제곱

array([ 1.    ,  4.    ,  9.8596, 17.64  , 26.01  ])

In [18]:
# 루트를 적용한 값을 출력
np.sqrt(arData)

array([1.        , 1.41421356, 1.77200451, 2.04939015, 2.25831796])

In [19]:
arVal = np.array([arData, arData ** 2])
arVal

array([[ 1.    ,  2.    ,  3.14  ,  4.2   ,  5.1   ],
       [ 1.    ,  4.    ,  9.8596, 17.64  , 26.01  ]])

In [20]:
arVal.sum(axis=0) # 축(axis)이 0일 경우 세로 축의 합을 출력

array([ 2.    ,  6.    , 12.9996, 21.84  , 31.11  ])

In [21]:
arVal.sum(axis=1) # 축(axis)이 0일 경우 가로 축의 합을 출력

array([15.44  , 58.5096])

In [22]:
# NumPy.array를 사용한 코드
np.array([[0,0,0],[0,0,0]])

array([[0, 0, 0],
       [0, 0, 0]])

In [23]:
# NumPy.zeros를 사용한 코드
arZero = np.zeros((2,3), dtype = 'i') 
arZero

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

**10.Pandas**

1)Series

In [80]:
# pandas import
import pandas as pd

pandas_series = pd.Series([30, 20, 10], index=['국어', '영어', '수학'])
print(type(pandas_series))
pandas_series

<class 'pandas.core.series.Series'>


국어    30
영어    20
수학    10
dtype: int64

In [81]:
pandas_series[1:]

영어    20
수학    10
dtype: int64

In [82]:
pandas_series[0]

30

In [83]:
pandas_series[0][1]

IndexError: ignored

2)DataFrame

In [84]:
df = pd.DataFrame([30,20,10], columns=['score'], index=['국어', '영어', '수학'])
df

score
국어     30
영어     20
수학     10

In [85]:
# DataFrame의 index를 표시
df.index

Index(['국어', '영어', '수학'], dtype='object')

In [86]:
# DataFrame의 column을 표시
df.columns

Index(['score'], dtype='object')

In [87]:
# DataFrame의index 중에서 국어에 해당하는 값을 출력
df.loc['국어']   # ix 함수가 최근 제거되어 loc를 써야 동작

score    30
Name: 국어, dtype: int64

In [88]:
# DataFrame의 값을 모두 합한 결과를 출력
df.sum()

score    60
dtype: int64

In [90]:
# DataFrame의 각 colimn 값의 제곱을 출력
df.score ** 2

국어    900
영어    400
수학    100
Name: score, dtype: int64

In [91]:
# DataFrame에 score2 라는 칼럼을 추가하고 값을 입력
df['score2'] = (50, 50, 50)
df

score  score2
국어     30      50
영어     20      50
수학     10      50

In [92]:
# DataFrame 함수를 이용하여 column을 추가할 수 있음
df['score2'] = pd.DataFrame([90,90,90], index=['국어', '영어', '수학'])
df

score  score2
국어     30      90
영어     20      90
수학     10      90

In [93]:
# column 삭제
del df['score']

In [95]:
# index 를 맞추기 않았을 경우
df['score2'] = (90, 90, 90, 100)

ValueError: ignored

In [94]:
# index 를 맞추기 않았을 경우
df['score2'] = pd.DataFrame([90, 90, 90, 100], index=['국어', '영어', '수학', '윤리'])
df

score2
국어      90
영어      90
수학      90

In [96]:
# join() 함수를 이용하여 2개의 DataFrame을 하나로 합칠 수 있음
df1 = pd.DataFrame([1, 2, 3], columns = ['A'])
df2 = pd.DataFrame([10, 11, 12, 13], columns = ['B'])

df = df1.join(df2, how='outer')
df

A   B
0  1.0  10
1  2.0  11
2  3.0  12
3  NaN  13

In [97]:
df_inner = df1.join(df2, how='inner')
df_inner

A   B
0  1  10
1  2  11
2  3  12

In [99]:
# 난수를 이용한 임의의 값 생성
df = pd.DataFrame(np.random.randn(5,5))
df.columns = ['A', 'B', 'C', 'D', 'E']
df

A         B         C         D         E
0 -1.050272  0.591262 -0.554342 -0.136844  1.789860
1  0.210399 -0.743306 -0.611347  1.043771 -0.207825
2 -1.434950  0.357785 -0.686082 -0.759811  0.328705
3 -1.174494  1.240429  0.714047  1.238566  1.199340
4 -1.792572  1.478652 -0.650520 -1.113720 -1.023295

In [100]:
# 최대값
df.max()

A    0.210399
B    1.478652
C    0.714047
D    1.238566
E    1.789860
dtype: float64

In [101]:
# 최소값
df.min()

A   -1.792572
B   -0.743306
C   -0.686082
D   -1.113720
E   -1.023295
dtype: float64

In [102]:
# 평균
df.mean()

A   -1.048378
B    0.584964
C   -0.357649
D    0.054392
E    0.417357
dtype: float64

In [103]:
# 표준편차
df.std()

A    0.758896
B    0.872391
C    0.601088
D    1.054173
E    1.114613
dtype: float64

In [104]:
# 누적값
df.cumsum()

A         B         C         D         E
0 -1.050272  0.591262 -0.554342 -0.136844  1.789860
1 -0.839872 -0.152044 -1.165689  0.906927  1.582034
2 -2.274823  0.205741 -1.851771  0.147116  1.910739
3 -3.449317  1.446170 -1.137723  1.385682  3.110079
4 -5.241889  2.924821 -1.788243  0.271962  2.086784

In [105]:
# DataFrame의 통계적 요약
df.describe()

A         B         C         D         E
count  5.000000  5.000000  5.000000  5.000000  5.000000
mean  -1.048378  0.584964 -0.357649  0.054392  0.417357
std    0.758896  0.872391  0.601088  1.054173  1.114613
min   -1.792572 -0.743306 -0.686082 -1.113720 -1.023295
25%   -1.434950  0.357785 -0.650520 -0.759811 -0.207825
50%   -1.174494  0.591262 -0.611347 -0.136844  0.328705
75%   -1.050272  1.240429 -0.554342  1.043771  1.199340
max    0.210399  1.478652  0.714047  1.238566  1.789860

In [106]:
# Group by를 이용한 DataFrame의 그룹화
df['division'] = ['X', 'Y', 'X', 'Y', 'Z']
df

A         B         C         D         E division
0 -1.050272  0.591262 -0.554342 -0.136844  1.789860        X
1  0.210399 -0.743306 -0.611347  1.043771 -0.207825        Y
2 -1.434950  0.357785 -0.686082 -0.759811  0.328705        X
3 -1.174494  1.240429  0.714047  1.238566  1.199340        Y
4 -1.792572  1.478652 -0.650520 -1.113720 -1.023295        Z

In [107]:
df.groupby(['division']).mean()

A         B         C         D         E
division                                                  
X        -1.242611  0.474524 -0.620212 -0.448328  1.059282
Y        -0.482047  0.248561  0.051350  1.141169  0.495757
Z        -1.792572  1.478652 -0.650520 -1.113720 -1.023295